### ISSUE TITLE
What do these SSDTs do?

### ISSUE THREAD

**Issue by Juan-VC-gh** [taina0407/T480-OpenCore-Hackintosh#10]
Can you briefly explain what are these SSDTs accomplishing?

SSDT-OCBAT0-TP.aml

SSDT-OCBATC-TP-NTFY.aml

I want to know because my laptop has 2 batteries and I am trying to implement them as one.
Thanks!

**Comment by benbender** [comment]
@Juan-VC Have a look at the docs @ https://github.com/acidanthera/VirtualSMC/blob/master/Docs/Dual%20Battery%20Support.md

**Comment by taina0407** [comment]
Sorry that I'm quite busy these day so I'm not able to maintain this project. Fortunaly, [EETagent](https://github.com/EETagent) has forked and seem actively maintaining it. So please go to [His repository](https://github.com/EETagent/T480-OpenCore-Hackintosh) for better EFI.
