### ISSUE TITLE
trackpad improvement

### ISSUE THREAD

**Issue by danny7g** [taina0407/T480-OpenCore-Hackintosh#11]
[VoodooPS2Controller.kext.zip](https://github.com/taina0407/T480-OpenCore-Hackintosh/files/4675057/VoodooPS2Controller.kext.zip)

I'm not sure why, but this version of VoodooPS2Controller works really well for me with no additional SSDT's.  I removed all trackpad related SSDT's from your EFI folder, too. Hopefully this helps.  

I got it from: https://github.com/mhanney/thinkpad-t480-hackintosh . There are related SSDT's and a supporting kext in this EFI, but through process of elimination, realized I just didn't need them.

**Comment by EETagent** [comment]
@danny7g 

As this repo was not updated for a long time, you could take a look at my fork. Touchpad gestures are OK with VoodooPS2Controller 2.1.4

https://github.com/EETagent/T480-OpenCore-Hackintosh

**Comment by danny7g** [comment]
thanks @EETagent ! I'll join you over there
