### ISSUE TITLE
SD card reader not detected, possible fix in SSDT-UIAC

### ISSUE THREAD

**Issue by afreuden** [taina0407/T480-OpenCore-Hackintosh#5]
Hi taina0407,

Thank you for developing this OpenCore build for the T480. I have been using it on my personal device for the past few days and noted that the SD card reader, or an inserted card is not detected. My device has an i5 8250U.

I will need to preface that I am completely new to the mackintosh scene, let alone using OpenCore. I did some research and cam across [https://github.com/kk1987/P52s-hackintosh](url) which suggests the configuration for a P52s would theoretically be similar to that of a T480 and T580.

It appears the SD card reader is using `SS03` and is detected as a USB card reader.

I added the following code to SSDT-UIAC adapted from kk1987s SSDT between `SS02` and `SS04`:
```
"SS03", 
Package (0x04)
{
    "UsbConnector", 
    0xFF, 
    "port", 
    Buffer (0x04)
    {
            0x0F, 0x00, 0x00, 0x00
    }
}, 
```

And amended `"ports", Package()` from `0x14` to `0x16`

I am uncertain if the `0x16` now exceeds the 15 port limit for macOS (Again, I am very new to this and am still learning). I have rebooted with the modified SSDT-UIAC and have confirmed the SD card reader is now functional with read/write and read only mode.

Thought I would share my findings.

I am curious to know how your device has SD card support without this addition? Perhaps there are subtle differences between the i5 8250U and i5 8320U boards?

Thanks!

**Comment by taina0407** [comment]
Hi @afreuden,

Thanks for your interesting and information.
As for my device, the USB Card Reader is working. I think I should mention that my T480 has Windows Hello Camera, I never tested other T480 configuration, but I think with these difference, we should map USB port again to make these device working properly.

In my case, I've tried to disable HS ports and SS ports and trying to find out all using USB ports and I've found that SD Card reader is using HS03 port only (I don't known why SS03 seem not map to SD Cardreader) so I've only enable this port only (and for my case, I'm not using SDCard alot, and I think that only USB2.0 for SDCard is enough for me).

About "And amended "ports", Package() from 0x14 to 0x16", I don't known why this make your SDCardreader work, but as I remember, Rehabman said that we should not change these "ports" at all.
BTW, my USB port map it not perfect yet (only 1.0.0 release, still alot of bugs). And I also find out that my device has 2 USB root device (one for regular USB, and other for thunderbolt ports). I still have no Thunderbolt devices to map out these correct port for now, so I suggest that you spend some time to map these port for your device.

I also suggest that you follow the guide, first disable all SS ports, using USB tab in Hackintool, check for each port and mapping correct ports, then repeat for HS ports.

**Comment by afreuden** [comment]
Hi taina0407,

Thanks, understandably everyone's USB mappings will potentially be very different across multiple T480 configurations. I only have the standard 720p web camera, no fancy IR sensors or anything.

That is really intriguing! I am a bit stumped as to why mine will only show up on an unlisted `SS03` 3.0 port rather than a `HS03` 2.0 port.

I had a look online and I can't seem to find an example where Rehabman defines a hex value for `"ports", Package()`?

Regrettably, I do not have any Thunderbolt or USB C devices that I can test either. Below is a mapping of the ports for my specific T480 spec (with the inclusion of `SS03` as the SD Card Reader):

|Port |Description|
|----|----|
|HS01|Right Bottom USB A 2.0|
|HS02|Right Top USB A 2.0|
|HS03|???|
|HS04|???|
|HS07|Bluetooth|
|HS08|Integrated Camera|
|HS09|Fingerprint Sensor|
|SS01|Right Bottom USB A 3.0|
|SS02|Right Top USB A 3.0|
|SS03|SD Card Reader|
|SS04|???|

If I were to use kk1987s SSDT as a reference, the non Thunderbolt USB Type C (for charging, but it does support PD, DP and USB) may be `HS04` and `SS04` though this is purely speculation without testing.

I too have 2 root USB devices, the latter being the Thunderbolt port which identifies as `pci8086,15c1`

I wonder if all we need is a second entry in UIAC for this as:
```
"8086_15c1",
Package (0x04)
{
    // mappings here
}
```

On another note, I do have a USB 3.1 device though Type A (`SDCZ430-064G`), I can confirm it is functional however runs at 3.0 speeds.

afreuden

**Comment by taina0407** [comment]
Hi @afreuden ,

Sorry for the late reply, I'm quite busy these days and not using my laptop much so not spend much time yet.
For another root USB device, I'm not sure that we can add second entry or not. And for the deviceId you provide, I can't see it matching in Rehabman template so I cannot sure that the kext will work for it or not.
The template here https://raw.githubusercontent.com/RehabMan/OS-X-USB-Inject-All/master/SSDT-UIAC-ALL.dsl
Rehabman mention about matching in template: 
> In the case of the NUC6i7KYK, it matches against a section in SSDT-UIAC-ALL.dsl that matches specifically against "8086_a12f". Some XHC devices will match against only part of the device-id. For example, the u430 device-id is 0x9c31. As there is no specific configuration for "8086_9c31", it will match against "8086_9xxx". Always use the template data that has the most specific match for your device-id. For example, if your device-id is 0x9cb1, you should use the template data for "8086_9cb1", not "8086_9xxx". Similarly, if your device id 0x9ded, use the template data 8086_9dxx, not 8086_9xxx.

He also mention about not changing Port address:
> Note: DO NOT CHANGE the port address assignments. All of the port addresses in SSDT-UIAC-ALL.dsl are correct. Changing them can only break things.

Source: https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

For my case, all the port works (only small problem is that the Dock Thunderbolt port only working as USB Type C 3.0 , 2.0 will not work. The Charging port still work with USB Type C both 2.0 and 3.0 event I haven't map the second root device)
I will try to map these device when I have free time

P/S: If you have time, please try to add second entry and add custom mapping to see it work or not, thanks

**Comment by taina0407** [comment]
Sorry that I'm quite busy these day so I'm not able to maintain this project. Fortunaly, [EETagent](https://github.com/EETagent) has forked and seem actively maintaining it. So please go to [His repository](https://github.com/EETagent/T480-OpenCore-Hackintosh) for better EFI.
