### ISSUE TITLE
TP i5-8250U 10.15.3 My issues | ver. 1.0.0

### ISSUE THREAD

**Issue by EETagent** [taina0407/T480-OpenCore-Hackintosh#6]
Hello,
I would like to report issues which I encountered so far.

1)~~SD reader doesn't work ( 2GB SD, 32GB SDHC ). I tried #5 too.~~
SD card reader started working now. Even though it didn't work whole day. Write and read is working on both cards. Still, these changes are temporary solution and new remap is needed. 
I will try to remap USB ports
2) Sidecar works really well ( No touch, only pencil. Not sure if touch is even supported. It doesn't work on MBA 2014 too. No supported Apple device to test ) with MBP15,2 SMBIOS. Didn't
 managed to get it working with MBP14,1
3) TrackPoint works but is unusable. With my testing EFI, I have managed to get TrackPoint working ( Scrolling sill triggers hyperlinks ). That made TrackPad unusable though.
4) TrackPad gestures
5) Wake sometimes works, sometimes doesn't. incompatible USB map and external SSD is probably reason here.
6) Occasional freezes. Probably because incompatible USB map ( see information bellow ). 

Everything above is tested using macOS 10.15.3 on external SATA SSD

My TP have cursed PM 981 drive. I have tried to update your EFI with newer version of NVMeFix.kext which should fix these issue. macOS Installer and macOS freezes every time. Tried it with my testing OC 0.5.8 EFI too. Random shutdowns and freezing.

**Comment by taina0407** [comment]
@EETagent Thanks for the information.
About freezes I think PM981 still unstable for hackintosh, so hard to say which really cause it :(

About trackpoint and trackpad still painful for me too, still looking for a correct way to implement it. If you found any solution, please let me now.

Thanks

**Comment by EETagent** [comment]
@taina0407 Could you please try newer version of NVMeFix on your machine when you will have free time?

Installation on PM981 with current version ( NVMeFix 1.0.1 ) predictably ends in kernel panic. But like I wrote week ago, when I try to simply replace older NVMeFix with the newer one, instllation USB or even installed system on external drive starts to freeze. I didn’t have any success with own testing EFI either.

**Comment by EETagent** [comment]
@taina0407 TrackPad - TrackPoint report:

I have got best results so far with included SSDT-Thinkpad_Trackpad. TrackPoint fully works now, scrolling doesn't trigger hyperlinks. TrackPad gestures and pointing works too. It's not perfectly smooth but usable. Force touch features must be disabled in settings, otherwise TrackPad would be unusable. 2 options at bottom called haptic feedback and quiet click.
![TrackPad](https://user-images.githubusercontent.com/20557318/80871400-b0ff3400-8cac-11ea-9e5e-806a9eb0b700.png)
