### ISSUE TITLE
Screen freezes from time to time, tested on T480 8550U with standard config.plist

### ISSUE THREAD

**Issue by ghost** [taina0407/T480-OpenCore-Hackintosh#8]
I have a T480 with dGPU (disabled with -wegnogpu flag), and there were times for the machine, running on macOS 10.15.4, to just froze its screen without getting a kernel panic message.

**Comment by taina0407** [comment]
Hi,

I'm not having T480 with dGPU so hard for me to diagnose this problem.
Please take a look for disable unsupported GPU guide here and try other methods to see could solve this or not https://dortania.github.io/OpenCore-Desktop-Guide/extras/spoof.html

Btw, your should take a look to iGPU patching too : https://dortania.github.io/OpenCore-Desktop-Guide/extras/gpu-patches.html

**Comment by ghost** [comment]
Thank you for your reply! I disabled that wegnogpu flag and used two SSDTs from https://github.com/tienhuynh5312/ThinkPad-T480-Hackintosh (DDGPU and PTSWAK) to disable the DGPU. I'll be keep testing this in the coming days. By the way, I found that the TrackPoint is very hard to use (e.g. sometimes it doesn't recognize me pressing the left button) without implementing the thinkpad-trackpad SSDT, but when I used that SSDT the touchpad is somehow very unresponsive unless I touch with heavy pressure. Is there something that I can change in the DSDT file to make it require less pressure? Thank you very much again!

**Comment by taina0407** [comment]
About the trackpoint and trackpad still very unstable for use, I'm quite busy these days, so I have not have time yet for fixing it yet. Will update when I found some thing. Stay tune :)

**Comment by ghost** [comment]
Sure, thanks!

**Comment by taina0407** [comment]
Sorry that I'm quite busy these day so I'm not able to maintain this project. Fortunaly, [EETagent](https://github.com/EETagent) has forked and seem actively maintaining it. So please go to [His repository](https://github.com/EETagent/T480-OpenCore-Hackintosh) for better EFI.
