### ISSUE TITLE
My OC 0.5.8 EFI | I5 8250U

### ISSUE THREAD

**Issue by EETagent** [taina0407/T480-OpenCore-Hackintosh#9]
My OC 0.5.8 EFI. SMBIOS 15,2  - different serial number etc.  Catalina 10.15.4.

- [x] USB-A Ports
- [x] SD Card reader
- [x] Charging USB-C port
- [ ]  Thunderbolt/USB-C port. Didn't map it. Only USB-C device that I have at hand currently is Nexus 5x which is probably only USB2. I think this port works only with USB3 devices.
- [ ]  Docking. No device to test.
- [x] Webcam
- [ ] Bluetooth device is mapped, but nothing works. `log show --last boot | grep IntelFirmware `doesn't print any output. #7 
- [x] Ethernet
- [x]  Wired Sidecar
- [x] TrackPoint is fully usable. Scrolling doesn't trigger hyperlinks. Same as Windows and Linux.
- [x] TrackPad is not perfectly smooth, but most 2,3 finger gestures and pointing works pretty well.  Force TrackPad features must be disabled. #6   
- [ ]  PM981. NVMeFix now doesn't make kernel panics. Didn't have time to wipe current Windows installation, but it should work without problems.
- [ ]  Battery life. Didn't tested so far. Intel Power Gadget shows 1,2-1,5 GHz average idle frequency
- [ ]  Perfomance. Lower Geekbench 5 scores, Cinebench R20 is almost the same. I'm currently testing VoltageShift undervolt. From terminal output I suggest it works. I have not saw any significant performance improvement.
- [x] HDMI output
- [x] HDMI Closed lid 
- [ ]  USB-C display output. No device to test
- [x] Sleep/Wake.  It could take long time ( Up to 20 sec ), before T480 enters sleep mode, but after that it works. Fans and screen are turned off. LED doesn't blink.
- [x] Battery charging threshold. I have set it to 80% in Windows. macOS stops charging at 83%. Probably at BIOS level.
- [x] Weird errors at first 2 seconds when booting. Reinstalled macOS. 
![Errors](https://user-images.githubusercontent.com/20557318/80914951-46eb9b00-8d4f-11ea-8493-7e69af9b9600.jpg) It firstly appeared when I upgraded to the OC 0.5.7. This EFI is mostly @taina0407 work. I've remapped ports, compiled newer version of IntelMausi.kext, added newer version of NVMeFix.kext and other kexts, added IntelBluetooth kexts, changed SMBIOS to be compatible with Sidecar, enabled SSDT-Thinkpad_Trackpad, cleaned config.plist little bit, removed unnecessary GPI-0.aml. 
In my opinion, there is too many renames in `<key>Patch</key>` section. I'm not hackintosh pro, so I don't know if they are all necessary. They could be the cause of the errors above.

Edit: Temporary deleted EFI. Yesterday I encountered disk corruption. When I reinstalled Catalina  those weird errors disappeared.  It's also different folder than I though. Nevermind. I worked whole day with the right EFI, everything was fine, but then mouse cursour disappeared. Keyboard worked ( Option&Space shortcut don't ), but the cursour was gone.

**Comment by taina0407** [comment]
Thanks @EETagent for your report.

I will take a look your EFI and try to implement Trackpad, (I've already did it before but seem doesn't work, will try again with your config as a template)

About rename in patching, all renames are required by SSDT, they are required because these SSDT will only apply for MacOS.
For example function A will be rename to function B, and in SSDT will create new fake A function, and then check if current OS is MacOS then will use new fake A one, else will use B function to avoid problems for windows and linux.

About these error look strange, but for me, not sure what is it >_<

**Comment by EETagent** [comment]
Now when OC 0.5.8 is officially released I realized some mistakes that I made. APFS is now built-in so no need for separate driver and Protocols section is now ProtocolOverrides. I have a theory why cursor could disappear. When it happens I need to reboot and my external drive could not be found in the UEFI boot menu. So I think, that my external drive disconnects at some time, that kills cursor, but some apps are already loaded in RAM so it partially works. Everything always goes wrong when I think it's working :(  I will try again on PM981, but definitely not before 7th May. Windows System Image backup is absolutely perfect  and blazing fast, but I still don't have time to do that.

**Comment by EETagent** [comment]
Here is it.
[EFI_UPLOAD.zip](https://github.com/taina0407/T480-OpenCore-Hackintosh/files/4605690/EFI_UPLOAD.zip)

- OpenCore 0.5.8
- Boot chime ( It may not work on other T480 models )
- OpenCanopy boot menu


Kernel extensions

- AppleALC 1.4.9
- IntelMausiEthernet 2.5.1.d1
- NVMeFix 1.0.2
- WhatEverGreen 1.3.9
- Lilu 1.4.4
- VirtualSMC 1.1.3
- IntelBluetoothFirmware | Injector - Disabled, doesn't work.
- VoodooPS2Controller 2.1.4 - Two finger swipes works really well now
-  USBInjectAll  0.7.1
- NoTouchID 1.0.3

UEFI Drivers

- HfsPlus.efi
- OpenRuntime.efi
- AudioDxe.efi
- OpenCanopy.efi

Changes could be merged.
https://github.com/EETagent/T480-OpenCore-Hackintosh
